import type { Lookbook, Product } from './types';

// ============================================
// 샘플 데이터 - DB 연결 전 시안용
// 실제 운영 시에는 Supabase에서 조회
// ============================================

export const SAMPLE_LOOKBOOKS: Lookbook[] = [
  {
    id: '1',
    slug: 'prada-lotte-jamsil-fall-2026',
    category: 'fashion',
    title_en: 'A study in quiet opulence',
    title_ko: '조용한 풍요로움에 대한 연구',
    publish_date: '2026-09-03',
    magazine: 'Fashion',
    client: 'PRADA — Lotte Jamsil',
    main_florist: 'YOON',
    sub_florist: 'CHOI',
    cover_image: '/images/lookbooks/prada-cover.jpg',
    gallery: [],
    video_url: null,
    article_en:
      'For the autumn unveiling at Lotte Jamsil, we draped the boutique in muted blooms — antique garden roses, smoked eucalyptus, dried hydrangea — composing a still life that whispered rather than declared.',
    article_ko:
      '잠실 롯데백화점 가을 신상 발표를 위해, 우리는 부티크를 차분한 꽃들로 채웠습니다 — 앤틱 가든 로즈, 스모크 유칼립투스, 드라이 하이드랜지아.',
    excerpt_en:
      'For the autumn unveiling at Lotte Jamsil, we draped the boutique in muted blooms — antique roses, smoked eucalyptus...',
    excerpt_ko: null,
    meta_title: 'PRADA Lotte Jamsil — Chezsua',
    meta_description: null,
    og_image: null,
    status: 'published',
    created_at: '2026-09-03T00:00:00Z',
    updated_at: '2026-09-03T00:00:00Z',
  },
  {
    id: '2',
    slug: 'four-seasons-seoul-anniversary',
    category: 'hotels',
    title_en: 'Lobby in bloom',
    title_ko: '꽃이 피어나는 로비',
    publish_date: '2026-08-21',
    magazine: 'Hotels',
    client: 'Four Seasons Seoul',
    main_florist: 'SUA',
    sub_florist: 'YOON',
    cover_image: '/images/lookbooks/four-seasons-cover.jpg',
    gallery: [],
    video_url: null,
    article_en:
      "A monumental centerpiece marking the hotel's tenth anniversary — sculpted from cymbidium orchids, white peony, and trailing greenery.",
    article_ko: '호텔 10주년을 기념하는 기념비적 센터피스 — 심비디움 난, 백작약, 그리고 흐르는 그린.',
    excerpt_en:
      "A monumental centerpiece marking the hotel's tenth anniversary — sculpted from cymbidium orchids, white peony...",
    excerpt_ko: null,
    meta_title: null,
    meta_description: null,
    og_image: null,
    status: 'published',
    created_at: '2026-08-21T00:00:00Z',
    updated_at: '2026-08-21T00:00:00Z',
  },
  {
    id: '3',
    slug: 'jeju-private-wedding',
    category: 'wedding',
    title_en: 'Vows by the sea',
    title_ko: '바닷가의 서약',
    publish_date: '2026-08-12',
    magazine: 'Wedding',
    client: 'Private — Jeju',
    main_florist: 'SUA',
    sub_florist: 'CHOI',
    cover_image: '/images/lookbooks/jeju-wedding-cover.jpg',
    gallery: [],
    video_url: 'https://youtube.com/watch?v=example',
    article_en:
      'An intimate ceremony framed by hand-tied bouquets of garden roses, ranunculus, and trailing jasmine — captured against the island wind.',
    article_ko:
      '가든 로즈, 라넌큘러스, 흐르는 자스민으로 만든 핸드타이드 부케로 둘러싸인 친밀한 예식 — 제주 바람을 배경으로.',
    excerpt_en:
      'An intimate ceremony framed by hand-tied bouquets of garden roses, ranunculus, and trailing jasmine — captured...',
    excerpt_ko: null,
    meta_title: null,
    meta_description: null,
    og_image: null,
    status: 'published',
    created_at: '2026-08-12T00:00:00Z',
    updated_at: '2026-08-12T00:00:00Z',
  },
  {
    id: '4',
    slug: 'mosu-seoul-tasting',
    category: 'fine-dining',
    title_en: 'Tabletop as theatre',
    title_ko: '극장으로서의 테이블',
    publish_date: '2026-07-29',
    magazine: 'Fine Dining',
    client: 'Mosu Seoul',
    main_florist: 'YOON',
    sub_florist: 'SUA',
    cover_image: '/images/lookbooks/mosu-cover.jpg',
    gallery: [],
    video_url: null,
    article_en:
      'A seasonal collaboration with chef Anh Sung-jae — twelve courses, twelve compositions, each a fleeting still life.',
    article_ko: '안성재 셰프와의 시즌 콜라보 — 12개 코스, 12개 구성, 각각이 순간의 정물화.',
    excerpt_en:
      'A seasonal collaboration with chef Anh Sung-jae — twelve courses, twelve compositions, each a fleeting still life...',
    excerpt_ko: null,
    meta_title: null,
    meta_description: null,
    og_image: null,
    status: 'published',
    created_at: '2026-07-29T00:00:00Z',
    updated_at: '2026-07-29T00:00:00Z',
  },
  {
    id: '5',
    slug: 'hermes-maison-dosan-fall',
    category: 'brands',
    title_en: 'An equestrian garden',
    title_ko: '승마의 정원',
    publish_date: '2026-07-14',
    magazine: 'Brands',
    client: 'Hermès — Maison Dosan',
    main_florist: 'SUA',
    sub_florist: null,
    cover_image: '/images/lookbooks/hermes-cover.jpg',
    gallery: [],
    video_url: null,
    article_en:
      "Maison Dosan's seasonal window — a meditation on the brand's equestrian heritage, told in saddle leather browns.",
    article_ko: '메종 도산의 시즌 윈도우 — 승마 헤리티지에 대한 명상, 안장 가죽의 갈색 톤으로.',
    excerpt_en:
      "Maison Dosan's seasonal window — a meditation on the brand's equestrian heritage, told in saddle leather browns...",
    excerpt_ko: null,
    meta_title: null,
    meta_description: null,
    og_image: null,
    status: 'published',
    created_at: '2026-07-14T00:00:00Z',
    updated_at: '2026-07-14T00:00:00Z',
  },
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'p1',
    slug: 'etude-in-rose',
    category: 'flower-bouquet',
    name_en: 'Étude in Rose',
    name_ko: '에튀드 인 로즈',
    description_en:
      'A hand-tied composition of antique garden roses, smoked eucalyptus, and trailing astrantia — wrapped in raw linen.',
    description_ko: '앤틱 가든 로즈, 스모크 유칼립투스, 아스트란시아의 핸드타이드 — 천연 린넨으로 감싸졌습니다.',
    care_en: 'Trim stems daily. Change water every 2 days.',
    care_ko: '매일 줄기를 다듬어 주세요. 물은 2일에 한 번 갈아주세요.',
    price_krw: 180000,
    price_usd: 135,
    images: [],
    options: [
      {
        name: 'Size',
        values: [
          { label: 'Small', price_diff: 0 },
          { label: 'Medium', price_diff: 30000 },
          { label: 'Large', price_diff: 70000 },
          { label: 'Grand', price_diff: 150000 },
        ],
      },
      {
        name: 'Wrap',
        values: [
          { label: 'Linen — Cream', price_diff: 0 },
          { label: 'Linen — Sage', price_diff: 0 },
          { label: 'Kraft', price_diff: -5000 },
        ],
      },
    ],
    pickup_available: true,
    delivery_available: true,
    stock: 12,
    status: 'active',
    is_new: true,
    is_best: false,
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'p2',
    slug: 'sage-whisper',
    category: 'flower-bouquet',
    name_en: 'Sage Whisper',
    name_ko: '세이지 휘스퍼',
    description_en: 'Subtle greens and creams in a meditative composition.',
    description_ko: '명상적인 구성의 은은한 그린과 크림.',
    care_en: null,
    care_ko: null,
    price_krw: 145000,
    price_usd: 110,
    images: [],
    options: [],
    pickup_available: true,
    delivery_available: true,
    stock: 8,
    status: 'active',
    is_new: false,
    is_best: false,
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'p3',
    slug: 'maison-pink',
    category: 'flower-bouquet',
    name_en: 'Maison Pink',
    name_ko: '메종 핑크',
    description_en: 'A statement piece in dusty rose tones.',
    description_ko: '더스티 로즈 톤의 시그니처 작품.',
    care_en: null,
    care_ko: null,
    price_krw: 220000,
    price_usd: 165,
    images: [],
    options: [],
    pickup_available: true,
    delivery_available: true,
    stock: 5,
    status: 'active',
    is_new: false,
    is_best: true,
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'p4',
    slug: 'forest-edition',
    category: 'flower-bouquet',
    name_en: 'Forest Edition',
    name_ko: '포레스트 에디션',
    description_en: 'Wild, foraged greens with seasonal blooms.',
    description_ko: '야생의 그린과 시즌 꽃의 조합.',
    care_en: null,
    care_ko: null,
    price_krw: 165000,
    price_usd: 124,
    images: [],
    options: [],
    pickup_available: true,
    delivery_available: true,
    stock: 7,
    status: 'active',
    is_new: false,
    is_best: false,
    created_at: '2026-04-01T00:00:00Z',
  },
];

/**
 * Helper - 색상 그라디언트 placeholder 생성 (실제 이미지 들어오기 전)
 */
export function getPlaceholderClass(seed: number): string {
  const palettes = [
    'bg-gradient-to-br from-[#E5C5BB] via-[#D9B7A0] to-[#B89882]',
    'bg-gradient-to-br from-[#E8DFC8] via-[#C9B98A] to-[#8FA68C]',
    'bg-gradient-to-br from-[#E5EDE3] via-[#C5B8A0] to-[#2D3F2E]',
    'bg-gradient-to-br from-[#E5C5BB] via-[#C9A0A0] to-[#8B5A6B]',
    'bg-gradient-to-br from-[#B5C2A8] via-[#8FA68C] to-[#4A5F4A]',
    'bg-gradient-to-br from-[#E8DFC8] via-[#B5A88E] to-[#6B5F4D]',
  ];
  return palettes[seed % palettes.length];
}
